# Generated by Django 4.2.5 on 2023-09-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="middle_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
